title: OSCAR
description: OSCAR is a tool to create beautiful, responsive Graphical User Interfaces to control interactive installations
show_downloads: true
google_analytics: UA-138608012-1
theme: jekyll-theme-cayman
twitter:
  username: trafalmejo
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/css/social-preview.jpg
        height: 630
        width: 1200
github:
  zip_url: https://github.com/trafalmejo/OSCAR/releases
  tar_url: https://github.com/trafalmejo/OSCAR/releases
